### PR TITLE
basic integration of ebyte E22 900M22S and E22 900M30S

### PR DESCRIPTION
**Pull request by netmonk**
Note that this should be exactly same code for other frequencies module such as 400mhz from Ebyte. 

This is basic integration. fully tested on both module as sender and receiver, On esp32-c3 (esp32-c3 devkitm-1 v1.0) with this pinout. 

MIso 2
Mosi 7
sck 6
nss 10
busy 18
nrst 19

DIO2 pin on Ebyte module must be connected to TXEN pin on Ebyte module

### CODE REVIEW

**Comment by nopnop2002** [comment]
Thank you for your PR.
I will update after reviewing.

**Comment by nopnop2002** [comment]
I am considering which one is better.

One way:

```
        choice MODULE
               prompt "sx126x module type" 
               default STANDARD
               help 
                       Select lora module model.
               config STANDARD
                      bool "STANDARD"
                      help 
                           Default choice to support RA* modules.
               config EBYTE
                      bool "EBYTE"
                      help
                           Ebyte module (E22 900M22S or E22 900M30S)
        endchoice              

#if CONFIG_EBYTE // Ebyte sx126* have external tcxo at 3.3v alimentation. 
	tcxoVoltage=3.3; // EBYTE is defined as a bool in kconfig menu
#endif
	if (tcxoVoltage > 0.0)
	{
		SetDio3AsTcxoCtrl(tcxoVoltage, RADIO_TCXO_SETUP_TIME); // Configure the radio to use a
	}
```


Other way:
```
	config USE_TCXO
		bool "Enable TCXO"
		default false
		help
			Enable TCXO.


#if CONFIG_USE_TCXO // Ebyte sx126* have external tcxo at 3.3v alimentation. 
	tcxoVoltage=3.3; // EBYTE is defined as a bool in kconfig menu
#endif
	if (tcxoVoltage > 0.0)
	{
		SetDio3AsTcxoCtrl(tcxoVoltage, RADIO_TCXO_SETUP_TIME); // Configure the radio to use a
	}
```

**Comment by netmonk** [comment]
i dont understand why i cannot see your comment about either using ebyte or tcxo. 

In fact it would be nice that kconfig allows to input float instead of integer. cause voltage is a float.
same for frequencies by the way. 

the best would be a top "use_tcxo" with a sub option "ebyte" which predefines 3.3v for those modules and anothor suboption to define other values for custom build.

**Comment by nopnop2002** [comment]
Here is Kconfig Language reference.

https://www.kernel.org/doc/html/latest/kbuild/kconfig-language.html


There is no float input.



I am thinking that I can choose:


Kconfig.projbuild:

```
	config USE_TXCO
		bool "Enable TXCO"
		default false
		help
			Enable TXCO.
```

```
	LoRaInit();
	//int ret = LoRaBegin(915000000, 22, 0.0, false);
	int8_t txPowerInDbm = 22;
	float tcxoVoltage = 0.0; // don't use TCXO
	bool useRegulatorLDO = false; // use only LDO in all modes

#if CONFIG_USE_TXCO // Use external tcxo at 3.3v alimentation. 
	tcxoVoltage = 3.3; // use TCXO
	useRegulatorLDO = true; // use TCXO
#endif

	//LoRaDebugPrint(true);
	int ret = LoRaBegin(frequencyInHz, txPowerInDbm, tcxoVoltage, useRegulatorLDO);
	ESP_LOGI(TAG, "LoRaBegin=%d", ret);
```

**Comment by netmonk** [comment]
ok i will patch accordingly

**Comment by netmonk** [comment]
Do you forget this one ?

**Comment by nopnop2002** [comment]
I don't have this module, so I commented the README.

**Comment by netmonk** [comment]
I dont understand this move, but do as you wish.

**Comment by nopnop2002** [comment]
Closed because I got reports that it works on ebyte E22 900M22S and E22 900M30S

**Comment by netmonk** [comment]
The other guy says it works without any proofs. From the documentation there is need to link dio2 to txen. This is common for anyone using properly this module. This PR is more  8months old  and I’m not sure which device the other guy is testing. 

Anyway, your behaviour on maintenant your library and integrating other’s contribution is quite strange. You only says you don’t have this module to test. But we were two with the concerned module and telling you it works and showing you proof of that. And you never accepted this pull request. 

You are clearly not serious.

**Comment by nopnop2002** [comment]
see here
https://github.com/nopnop2002/esp-idf-sx126x/issues/17

**Pull request closed without merging**
