### PR TITLE
Added retry loop to fix SPI Transaction error

### PR DESCRIPTION
**Pull request by Glowman554**
Tested on heltec lora v3 board. Datasheet can be found here; https://resource.heltec.cn/download/HTIT-WB32LA_V3(Rev1.1).pdf

### CODE REVIEW

**Comment by nopnop2002** [comment]
Isn't this better?

```
//for (uint8_t retry = 1; (in == 0xaa) && (retry < 10); retry++) {
for (uint8_t retry = 1; (in != 0xa2) && (retry < 10); retry++) {
```

**Comment by Glowman554** [comment]
Heyy i tested it and it works. I pushed the change

**Comment by nopnop2002** [comment]
I would like you to change it to the following and test it.
		for (uint8_t retry = 1; (in != 0xa2) && (retry < 10); retry++) {
			if(debugPrint) {
				ESP_LOGI(TAG, "%02x --> %02x", data[n], in);
			}
			
			gpio_set_level(SX126x_SPI_SELECT, HIGH);
			WaitForIdle(BUSY_WAIT);
			gpio_set_level(SX126x_SPI_SELECT, LOW);
			//spi_transfer(cmd);
			in = spi_transfer(data[n]);

			if (debugPrint) {
				ESP_LOGW(TAG, "RETRY: Try=%d", retry);
			}

		}

**Comment by Glowman554** [comment]
Hi, i tested it and it causes the same error

**Comment by nopnop2002** [comment]
@Glowman554 

I am concerned that it will not work correctly in the following cases.

numBytes>1
spi_transfer(cmd);
spi_transfer(data[0]); --> OK
spi_transfer(data[1]); --> FAIL
spi_transfer(cmd);
spi_transfer(data[1]); --> FAIL


```
void WriteCommand(uint8_t cmd, uint8_t* data, uint8_t numBytes) {
	// ensure BUSY is low (state meachine ready)
	WaitForIdle(BUSY_WAIT);

	// start transfer
	gpio_set_level(SX126x_SPI_SELECT, LOW);
	//SPI.beginTransaction(SPISettings(2000000, MSBFIRST, SPI_MODE0));

	// send command byte
	if(debugPrint) {
		ESP_LOGI(TAG, "WriteCommand: CMD=0x%02x", cmd);
	}
	spi_transfer(cmd);

	// variable to save error during SPI transfer
	uint8_t status = 0;

	// send/receive all bytes
	for(uint8_t n = 0; n < numBytes; n++) {
		uint8_t in = spi_transfer(data[n]);
		
		for (uint8_t retry = 1; (in != 0xa2) && (retry < 10); retry++) {
			if(debugPrint) {
				ESP_LOGI(TAG, "%02x --> %02x", data[n], in);
			}
			
			gpio_set_level(SX126x_SPI_SELECT, HIGH);
			WaitForIdle(BUSY_WAIT);
			gpio_set_level(SX126x_SPI_SELECT, LOW);
			spi_transfer(cmd);
			in = spi_transfer(data[n]);

			if (debugPrint) {
				ESP_LOGW(TAG, "RETRY: Try=%d", retry);
			}

		}


		// check status
		if(((in & 0b00001110) == SX126X_STATUS_CMD_TIMEOUT) ||
		 ((in & 0b00001110) == SX126X_STATUS_CMD_INVALID) ||
		 ((in & 0b00001110) == SX126X_STATUS_CMD_FAILED)) {
			status = in & 0b00001110;
			break;
		} else if(in == 0x00 || in == 0xFF) {
			status = SX126X_STATUS_SPI_FAILED;
			break;
		}
	} 

	// stop transfer
	//SPI.endTransaction();
	gpio_set_level(SX126x_SPI_SELECT, HIGH);

	// wait for BUSY to go low
	WaitForIdle(BUSY_WAIT);
#if 0
	if(waitForBusy) {
		WaitForIdle(BUSY_WAIT);
	}
#endif

	if (status != 0) {
		ESP_LOGE(TAG, "SPI Transaction error:%d", status);
		while(1) { vTaskDelay(1); }
	}
}
```

**Comment by nopnop2002** [comment]
The heltec lora v3 board has an Onboard 0.96-inch 128*64 dot matrix OLED display.
Are you experiencing SPI bus contention?

**Comment by Glowman554** [comment]
as far as i know the oled display is connected using i²c and shouldnt interfere with the spi bus

**Comment by nopnop2002** [comment]
What do you see below in your original code when you get an error?

```
ESP_LOGE(TAG, "SPI Transaction error:%d", status);
```

**Comment by Glowman554** [comment]
I see error: 10. Also the retry only triggers once at the begining and after that it doesn't trigger again as far as i can see.

**Comment by Glowman554** [comment]
Also sorry but i can't test / send logs now since im not home

**Comment by nopnop2002** [comment]
Added retry code to WriteCommand function.

Try latest.

**Comment by Glowman554** [comment]
It works. Thx

**Comment by nopnop2002** [comment]
I want to see the debug logging when retries are occurring.

**Comment by Glowman554** [comment]
```
I (347) gpio: GPIO[13]| InputEn: 0| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0
I (357) RA01S: spi_bus_initialize=0
I (357) RA01S: spi_bus_add_device=0
I (407) RA01S: Reset
I (407) RA01S: ReadRegister: REG=0x740
I (407) RA01S: DataIn:14
I (407) RA01S: DataIn:24
I (407) RA01S: syncWord=0x1424
I (407) RA01S: SX126x installed
I (417) RA01S: WriteCommand: CMD=0x80
I (417) RA01S: 00 --> aa
W (417) RA01S: WriteCommand2 status=0a retry=1
I (427) RA01S: WriteCommand: CMD=0x80
I (427) RA01S: 00 --> a2
I (437) RA01S: WriteCommand: CMD=0x9d
I (437) RA01S: 01 --> a2
I (437) RA01S: tcxoVoltage=1.800000
I (447) RA01S: WriteCommand: CMD=0x97
```

This is the only time when the retry happens

**Comment by nopnop2002** [comment]
Thank you.

**Pull request merged**
