### PR TITLE
better error handling

### PR DESCRIPTION
**Pull request by Glowman554**
Just define a LoRaError(int error) function. If not defined LoRaErrorDefault is used

### CODE REVIEW

**Comment by nopnop2002** [comment]
Is this return required?

```
		if(xTaskGetTickCount() - start >= (timeout/portTICK_PERIOD_MS)) {
			ESP_LOGE(TAG, "WaitForIdle Timeout timeout=%lu", timeout);
			LoRaError(ERR_IDLE_TIMEOUT);
			return;
		}
```

**Comment by Glowman554** [comment]
it is there that if the error function returns that the function does not execute code even though a error happened

**Comment by nopnop2002** [comment]
I don't understand your content.


LoRaError() is an endless loop and does not return.

```
void LoRaErrorDefault(int error)
{
	if (debugPrint) {
		ESP_LOGE(TAG, "LoRaErrorDefault=%d", error);
	}
	while (true) {
		vTaskDelay(1);
	}
}

__attribute__ ((weak, alias ("LoRaErrorDefault"))) void LoRaError(int error);
```

**Comment by nopnop2002** [comment]
I still don't understand your point of view.

It is no longer safe for the user-defined function to return at this point.
```
	if ((GetStatus() & 0x70) != 0x60) {
		ESP_LOGE(TAG, "SetTx Illegal Status");
		LoRaError(ERR_INVALID_SETTX_STATE);
	}
```

**Comment by nopnop2002** [comment]
As for WaitForIdle(), if it doesn't become Idle for a certain period of time, I don't think you can ignore it and continue processing.

**Comment by nopnop2002** [comment]
Well, let's get back on topic.

The purpose of this assignment was to automatically restart when an error was detected.

What are its advantages?

I don't understand the advantage.

**Comment by Glowman554** [comment]
rebooting isnt the only option to handle the error. i would like to exit the task and send a error message in my project. one possible example is the spi transaction error i had

**Comment by Glowman554** [comment]
the advantage is that the user decides what happens when a error happend

**Comment by nopnop2002** [comment]
> i would like to exit the task and send a error message in my project. 

this is a good idea.

>the advantage is that the user decides what happens when a error happend

I see.

Adding a return here doesn't make sense.

The operation is the same whether there is a return or not.

```
void WaitForIdle(unsigned long timeout)
{
    //unsigned long start = millis();
    TickType_t start = xTaskGetTickCount();
    delayMicroseconds(1);
    while(gpio_get_level(SX126x_BUSY)) {
        delayMicroseconds(1);
        //if(millis() - start >= timeout) {
        if(xTaskGetTickCount() - start >= (timeout/portTICK_PERIOD_MS)) {
            ESP_LOGE(TAG, "WaitForIdle Timeout timeout=%lu", timeout);
            LoRaError(ERR_IDLE_TIMEOUT);
            //return;
        }
    }
}
```

**Comment by nopnop2002** [comment]
This allows the user to specify whether to continue, quit, or restart when an error occurs.
```
void WaitForIdle(unsigned long timeout)
{
    //unsigned long start = millis();
    TickType_t start = xTaskGetTickCount();
    delayMicroseconds(1);
    while(xTaskGetTickCount() - start < (timeout/portTICK_PERIOD_MS)) {
        if (gpio_get_level(SX126x_BUSY) == 0) break;
        delayMicroseconds(1);
    }
    if (gpio_get_level(SX126x_BUSY)) {
      ESP_LOGE(TAG, "WaitForIdle Timeout timeout=%lu", timeout);
      LoRaError(ERR_IDLE_TIMEOUT);
    }
}
```

**Comment by Glowman554** [comment]
tbh i don't see how that changes anything but i changed it anyways

**Comment by Glowman554** [comment]
Anything new?

**Comment by nopnop2002** [comment]
I support issues for other libraries.

please wait a little bit.

**Comment by Glowman554** [comment]
Anything new?

**Comment by nopnop2002** [comment]
Now testing.

**Comment by Glowman554** [comment]
Anything new?

**Pull request merged**
